import { Item } from "../types.js";

const TOPIC = "four-operations-fractions";

export const FOUR_OPERATIONS_FRACTIONS_ITEMS: Item[] = [
  // --- CONCRETE ---
  {
    id: "fo-c-remember",
    topicId: TOPIC,
    cpa: "concrete",
    bloom: "remember",
    subskill: "add-subtract-like",
    prompt: "You combine 2/5 of a basket of oranges with 1/5 of the same basket. Which operation combines these shares?",
    representation: { kind: "concrete", icon: "🍊", itemCount: 5, groups: 1, groupLabel: "basket" },
    choices: [
      { id: "a", text: "Addition" },
      { id: "b", text: "Subtraction" },
      { id: "c", text: "Multiplication" },
      { id: "d", text: "Division" },
    ],
    correctChoiceId: "a",
  },
  {
    id: "fo-c-understand",
    topicId: TOPIC,
    cpa: "concrete",
    bloom: "understand",
    subskill: "add-subtract-like",
    prompt: "3/8 of a bag of marbles are red and 2/8 are blue. Using the counters shown, what fraction of the bag is red or blue?",
    representation: {
      kind: "concrete",
      icon: "🔴",
      itemCount: 8,
      groups: 1,
      groupLabel: "bag",
      segments: [
        { icon: "🔴", count: 3, label: "red" },
        { icon: "🔵", count: 2, label: "blue" },
        { icon: "⚪", count: 3, label: "neither" },
      ],
    },
    choices: [
      { id: "a", text: "5/8" },
      { id: "b", text: "1/8" },
      { id: "c", text: "6/8" },
      { id: "d", text: "5/16" },
    ],
    correctChoiceId: "a",
  },
  {
    id: "fo-c-apply",
    topicId: TOPIC,
    cpa: "concrete",
    bloom: "apply",
    subskill: "multiply-fractions",
    prompt: "There are 12 candies. 1/3 of them are given away, and then 1/2 of what was given away is eaten. Using the objects, how many candies were eaten?",
    representation: { kind: "concrete", icon: "🍬", itemCount: 12, groups: 3, groupLabel: "groups" },
    choices: [
      { id: "a", text: "2" },
      { id: "b", text: "4" },
      { id: "c", text: "6" },
      { id: "d", text: "3" },
    ],
    correctChoiceId: "a",
  },
  {
    id: "fo-c-analyze",
    topicId: TOPIC,
    cpa: "concrete",
    bloom: "analyze",
    subskill: "add-subtract-unlike",
    prompt: "A tray of 10 cookies has 3/5 iced with chocolate. How many cookies are NOT chocolate-iced?",
    representation: { kind: "concrete", icon: "🍪", itemCount: 10, groups: 5, groupLabel: "groups" },
    choices: [
      { id: "a", text: "4" },
      { id: "b", text: "6" },
      { id: "c", text: "3" },
      { id: "d", text: "5" },
    ],
    correctChoiceId: "a",
  },
  {
    id: "fo-c-evaluate",
    topicId: TOPIC,
    cpa: "concrete",
    bloom: "evaluate",
    subskill: "multiply-fractions",
    prompt: "A student modeled '3/4 of 8 apples' by grouping 8 apples into 3 equal groups and counting 4. Is this correct?",
    representation: { kind: "concrete", icon: "🍎", itemCount: 8, groups: 3, groupLabel: "groups" },
    choices: [
      { id: "a", text: "No — 8 should be split into 4 equal groups, then take 3 of those groups" },
      { id: "b", text: "Yes, that's correct" },
      { id: "c", text: "No, apples cannot be grouped" },
      { id: "d", text: "Yes, because 3 and 4 can be swapped" },
    ],
    correctChoiceId: "a",
  },

  // --- PICTORIAL (word-problem / model-setup heavy, per design doc) ---
  {
    id: "fo-p-remember",
    topicId: TOPIC,
    cpa: "pictorial",
    bloom: "remember",
    subskill: "add-subtract-like",
    prompt: "The bar model shows 3/4 shaded out of a whole bar split into 4 equal parts. What fraction is NOT shaded?",
    representation: { kind: "bar-model", totalLabel: "1 whole", parts: 4, highlightParts: 3 },
    choices: [
      { id: "a", text: "1/4" },
      { id: "b", text: "3/4" },
      { id: "c", text: "1/3" },
      { id: "d", text: "4/3" },
    ],
    correctChoiceId: "a",
  },
  {
    id: "fo-p-understand",
    topicId: TOPIC,
    cpa: "pictorial",
    bloom: "understand",
    subskill: "add-subtract-like",
    prompt: "Raj eats 2/6 of a cake and Mia eats 1/6 of the same cake, shown on the bar model. What fraction of the cake did they eat together?",
    representation: {
      kind: "bar-model",
      totalLabel: "1 cake",
      parts: 6,
      highlightGroups: [
        { count: 2, label: "Raj: 2/6" },
        { count: 1, label: "Mia: 1/6" },
      ],
    },
    choices: [
      { id: "a", text: "3/6 (½)" },
      { id: "b", text: "1/6" },
      { id: "c", text: "2/6" },
      { id: "d", text: "3/12" },
    ],
    correctChoiceId: "a",
  },
  {
    id: "fo-p-apply",
    topicId: TOPIC,
    cpa: "pictorial",
    bloom: "apply",
    subskill: "word-problem-setup",
    prompt: "A ribbon is 5/6 m long. Priya uses 1/3 m of it. Using the bar model, how much ribbon is left?",
    representation: {
      kind: "bar-model",
      totalLabel: "5/6 m ribbon (the 6th part is not part of the ribbon at all)",
      parts: 6,
      highlightGroups: [
        { count: 2, label: "used: 1/3 m (2/6)" },
        { count: 3, label: "remaining ribbon" },
      ],
    },
    choices: [
      { id: "a", text: "1/2 m" },
      { id: "b", text: "2/3 m" },
      { id: "c", text: "4/9 m" },
      { id: "d", text: "5/18 m" },
    ],
    correctChoiceId: "a",
  },
  {
    id: "fo-p-analyze",
    topicId: TOPIC,
    cpa: "pictorial",
    bloom: "analyze",
    subskill: "word-problem-setup",
    prompt: "A jug has 3/4 L of juice, shown on the bar model (drawn in eighths so the half-pour splits evenly). Half of it is poured into a glass. Which amount was poured?",
    representation: {
      kind: "bar-model",
      totalLabel: "3/4 L juice = 6/8 L (the last 2/8 is not part of the juice at all)",
      parts: 8,
      highlightGroups: [
        { count: 3, label: "poured into glass: 3/8 L" },
        { count: 3, label: "remains in jug" },
      ],
    },
    choices: [
      { id: "a", text: "3/8 L, because half of 3/4 is 3/8" },
      { id: "b", text: "1/2 L, because the glass just needs half a liter" },
      { id: "c", text: "3/4 L, because all the juice moves" },
      { id: "d", text: "1/4 L" },
    ],
    correctChoiceId: "a",
  },
  {
    id: "fo-p-evaluate",
    topicId: TOPIC,
    cpa: "pictorial",
    bloom: "evaluate",
    subskill: "word-problem-setup",
    prompt: "Tom has 2/3 of a pizza. He gives 1/4 of his share to his sister. Which bar-model setup correctly represents 'his share' before finding 1/4 of it?",
    representation: { kind: "bar-model", totalLabel: "1 pizza", parts: 3, highlightParts: 2 },
    choices: [
      { id: "a", text: "A bar showing the whole pizza split into 3 parts, with 2 of those parts marked as Tom's share, then split further into 4" },
      { id: "b", text: "A bar split into 4 parts directly, ignoring the 2/3" },
      { id: "c", text: "A bar split into 3 parts representing the sister's share" },
      { id: "d", text: "A bar split into 7 parts (3 + 4)" },
    ],
    correctChoiceId: "a",
  },

  // --- ABSTRACT (pure computation) ---
  {
    id: "fo-a-remember",
    topicId: TOPIC,
    cpa: "abstract",
    bloom: "remember",
    subskill: "add-subtract-like",
    prompt: "1/4 + 2/4 = ?",
    representation: null,
    choices: [
      { id: "a", text: "3/4" },
      { id: "b", text: "3/8" },
      { id: "c", text: "2/4" },
      { id: "d", text: "1/16" },
    ],
    correctChoiceId: "a",
  },
  {
    id: "fo-a-understand",
    topicId: TOPIC,
    cpa: "abstract",
    bloom: "understand",
    subskill: "add-subtract-unlike",
    prompt: "Why is 1/2 + 1/3 NOT equal to 2/5?",
    representation: null,
    choices: [
      { id: "a", text: "Because fractions need a common denominator before adding numerators" },
      { id: "b", text: "Because 2/5 is too small" },
      { id: "c", text: "Because you should multiply instead" },
      { id: "d", text: "Because 1/2 and 1/3 can't be added" },
    ],
    correctChoiceId: "a",
  },
  {
    id: "fo-a-apply",
    topicId: TOPIC,
    cpa: "abstract",
    bloom: "apply",
    subskill: "add-subtract-unlike",
    prompt: "Compute: 5/6 − 1/3 = ?",
    representation: null,
    choices: [
      { id: "a", text: "1/2" },
      { id: "b", text: "4/3" },
      { id: "c", text: "4/6" },
      { id: "d", text: "2/3" },
    ],
    correctChoiceId: "a",
  },
  {
    id: "fo-a-analyze",
    topicId: TOPIC,
    cpa: "abstract",
    bloom: "analyze",
    subskill: "multiply-fractions",
    prompt: "Which computation below contains an error?\nA) 2/3 × 3/4 = 6/12 = 1/2\nB) 1/2 + 1/4 = 2/6\nC) 5/8 − 1/8 = 4/8 = 1/2\nD) 2/5 × 5/2 = 10/10 = 1",
    representation: null,
    choices: [
      { id: "a", text: "A" },
      { id: "b", text: "B" },
      { id: "c", text: "C" },
      { id: "d", text: "D" },
    ],
    correctChoiceId: "b",
  },
  {
    id: "fo-a-evaluate",
    topicId: TOPIC,
    cpa: "abstract",
    bloom: "evaluate",
    subskill: "multiply-fractions",
    prompt: "A student says: '3/4 × 2/3 will always give a bigger number than 3/4, because multiplication makes things bigger.' Evaluate this claim.",
    representation: null,
    choices: [
      { id: "a", text: "False — multiplying by a fraction less than 1 makes the result smaller (3/4 × 2/3 = 1/2, which is less than 3/4)" },
      { id: "b", text: "True, multiplication always increases value" },
      { id: "c", text: "False, but only because 2/3 is negative" },
      { id: "d", text: "True, as long as both fractions are positive" },
    ],
    correctChoiceId: "a",
  },
];
