import { Item } from "../types.js";

const TOPIC = "fractions-division";

export const FRACTIONS_DIVISION_ITEMS: Item[] = [
  // --- CONCRETE ---
  {
    id: "fd-c-remember",
    topicId: TOPIC,
    cpa: "concrete",
    bloom: "remember",
    subskill: "equal-sharing",
    prompt: "Look at the 4 rotis being shared equally among 2 children. What does 'shared equally' mean here?",
    representation: { kind: "concrete", icon: "🥯", itemCount: 4, groups: 2, groupLabel: "children" },
    choices: [
      { id: "a", text: "Each child gets the same amount" },
      { id: "b", text: "One child gets more because they asked first" },
      { id: "c", text: "The rotis are shared based on age" },
      { id: "d", text: "It doesn't matter how they are shared" },
    ],
    correctChoiceId: "a",
  },
  {
    id: "fd-c-understand",
    topicId: TOPIC,
    cpa: "concrete",
    bloom: "understand",
    subskill: "equal-sharing",
    prompt: "6 laddus are shared equally among 3 children, shown below. How many laddus does each child receive?",
    representation: { kind: "concrete", icon: "🍡", itemCount: 6, groups: 3, groupLabel: "children" },
    choices: [
      { id: "a", text: "2" },
      { id: "b", text: "3" },
      { id: "c", text: "6" },
      { id: "d", text: "1" },
    ],
    correctChoiceId: "a",
  },
  {
    id: "fd-c-apply",
    topicId: TOPIC,
    cpa: "concrete",
    bloom: "apply",
    subskill: "fraction-notation",
    prompt: "5 mangoes are shared equally among 2 children. Which expression shows how many mangoes each child gets?",
    representation: { kind: "concrete", icon: "🥭", itemCount: 5, groups: 2, groupLabel: "children" },
    choices: [
      { id: "a", text: "5 ÷ 2" },
      { id: "b", text: "2 ÷ 5" },
      { id: "c", text: "5 × 2" },
      { id: "d", text: "5 − 2" },
    ],
    correctChoiceId: "a",
  },
  {
    id: "fd-c-analyze",
    topicId: TOPIC,
    cpa: "concrete",
    bloom: "analyze",
    subskill: "unit-fraction-reasoning",
    prompt: "7 idlis are shared equally among 4 children. Priya says each child gets less than 2 idlis. Is she correct?",
    representation: { kind: "concrete", icon: "🍚", itemCount: 7, groups: 4, groupLabel: "children" },
    choices: [
      { id: "a", text: "Yes, because 7 ÷ 4 is between 1 and 2" },
      { id: "b", text: "No, because 7 ÷ 4 is more than 2" },
      { id: "c", text: "Yes, because 7 is less than 8" },
      { id: "d", text: "No, because idlis can't be shared equally" },
    ],
    correctChoiceId: "a",
  },
  {
    id: "fd-c-evaluate",
    topicId: TOPIC,
    cpa: "concrete",
    bloom: "evaluate",
    subskill: "word-problem-setup",
    prompt: "A teacher wants to represent the fraction 3/5 using concrete counters for the class. Which setup best represents it?",
    representation: { kind: "concrete", icon: "●", itemCount: 3, groups: 5, groupLabel: "groups" },
    choices: [
      { id: "a", text: "3 counters shared equally among 5 groups; one group's share is the fraction" },
      { id: "b", text: "5 counters shared equally among 3 groups" },
      { id: "c", text: "3 groups of 5 counters each" },
      { id: "d", text: "5 groups of 3 counters, added together" },
    ],
    correctChoiceId: "a",
  },

  // --- PICTORIAL ---
  {
    id: "fd-p-remember",
    topicId: TOPIC,
    cpa: "pictorial",
    bloom: "remember",
    subskill: "fraction-notation",
    prompt: "The bar below shows 3 rotis divided into 4 equal parts. What fraction of a roti does one part represent?",
    representation: { kind: "bar-model", totalLabel: "3 rotis", parts: 4 },
    choices: [
      { id: "a", text: "1/4" },
      { id: "b", text: "1/3" },
      { id: "c", text: "4/3" },
      { id: "d", text: "3/4" },
    ],
    correctChoiceId: "a",
  },
  {
    id: "fd-p-understand",
    topicId: TOPIC,
    cpa: "pictorial",
    bloom: "understand",
    subskill: "equal-sharing",
    prompt: "Amma divides 3 rotis equally among 4 children. Which bar model correctly shows how much roti each child gets?",
    representation: { kind: "bar-model", totalLabel: "3 rotis / 4 children", parts: 4 },
    choices: [
      { id: "a", text: "Each child gets ¾ of a roti" },
      { id: "b", text: "Each child gets ⅓ of a roti" },
      { id: "c", text: "Each child gets 1¼ rotis" },
      { id: "d", text: "Each child gets 4 pieces of ⅓ each" },
    ],
    correctChoiceId: "a",
  },
  {
    id: "fd-p-apply",
    topicId: TOPIC,
    cpa: "pictorial",
    bloom: "apply",
    subskill: "word-problem-setup",
    prompt: "5 cakes are shared equally among 4 friends. Using the bar model idea, how much cake does each friend get?",
    representation: { kind: "bar-model", totalLabel: "5 cakes", parts: 4 },
    choices: [
      { id: "a", text: "5/4 (1¼) cakes" },
      { id: "b", text: "4/5 cakes" },
      { id: "c", text: "1/5 cakes" },
      { id: "d", text: "5 cakes each" },
    ],
    correctChoiceId: "a",
  },
  {
    id: "fd-p-analyze",
    topicId: TOPIC,
    cpa: "pictorial",
    bloom: "analyze",
    subskill: "unit-fraction-reasoning",
    prompt: "The bar model shows 7 sandwiches shared equally among 3 children. Which statement about each child's share is correct?",
    representation: { kind: "bar-model", totalLabel: "7 sandwiches", parts: 3 },
    choices: [
      { id: "a", text: "Each child gets 7/3 sandwiches, which is more than 2 whole sandwiches" },
      { id: "b", text: "Each child gets 3/7 of a sandwich" },
      { id: "c", text: "Each child gets exactly 2 sandwiches" },
      { id: "d", text: "Each child gets less than 1 sandwich" },
    ],
    correctChoiceId: "a",
  },
  {
    id: "fd-p-evaluate",
    topicId: TOPIC,
    cpa: "pictorial",
    bloom: "evaluate",
    subskill: "word-problem-setup",
    prompt: "Two students drew different bar models for '4 pizzas shared equally among 5 people.' Which bar model correctly represents the situation?",
    representation: { kind: "bar-model", totalLabel: "4 pizzas", parts: 5 },
    choices: [
      { id: "a", text: "A bar of 4 units split into 5 equal parts, each part = 4/5" },
      { id: "b", text: "A bar of 5 units split into 4 equal parts, each part = 5/4" },
      { id: "c", text: "A bar split into 4 parts with no reference to the 5 people" },
      { id: "d", text: "A bar split into 9 equal parts" },
    ],
    correctChoiceId: "a",
  },

  // --- ABSTRACT ---
  {
    id: "fd-a-remember",
    topicId: TOPIC,
    cpa: "abstract",
    bloom: "remember",
    subskill: "fraction-notation",
    prompt: "Which expression is equivalent to 3 ÷ 4?",
    representation: null,
    choices: [
      { id: "a", text: "3/4" },
      { id: "b", text: "4/3" },
      { id: "c", text: "3 × 4" },
      { id: "d", text: "4 − 3" },
    ],
    correctChoiceId: "a",
  },
  {
    id: "fd-a-understand",
    topicId: TOPIC,
    cpa: "abstract",
    bloom: "understand",
    subskill: "fraction-notation",
    prompt: "What does the fraction 5/8 represent in terms of division?",
    representation: null,
    choices: [
      { id: "a", text: "5 divided by 8" },
      { id: "b", text: "8 divided by 5" },
      { id: "c", text: "5 multiplied by 8" },
      { id: "d", text: "8 minus 5" },
    ],
    correctChoiceId: "a",
  },
  {
    id: "fd-a-apply",
    topicId: TOPIC,
    cpa: "abstract",
    bloom: "apply",
    subskill: "fraction-notation",
    prompt: "Compute 9 ÷ 6, giving your answer as a fraction in simplest form.",
    representation: null,
    choices: [
      { id: "a", text: "3/2" },
      { id: "b", text: "2/3" },
      { id: "c", text: "9/6" },
      { id: "d", text: "1/2" },
    ],
    correctChoiceId: "a",
  },
  {
    id: "fd-a-analyze",
    topicId: TOPIC,
    cpa: "abstract",
    bloom: "analyze",
    subskill: "unit-fraction-reasoning",
    prompt: "If a ÷ b = 5/3, which of the following must be true?",
    representation: null,
    choices: [
      { id: "a", text: "a is greater than b" },
      { id: "b", text: "a is less than b" },
      { id: "c", text: "a equals b" },
      { id: "d", text: "a must be an even number" },
    ],
    correctChoiceId: "a",
  },
  {
    id: "fd-a-evaluate",
    topicId: TOPIC,
    cpa: "abstract",
    bloom: "evaluate",
    subskill: "word-problem-setup",
    prompt: "A recipe divides 11 cups of flour equally among 4 batches. Which expression and reasoning correctly finds the amount per batch?",
    representation: null,
    choices: [
      { id: "a", text: "11 ÷ 4 = 11/4, because dividing a quantity into equal groups is the same as writing it as a fraction" },
      { id: "b", text: "4 ÷ 11 = 4/11, because the smaller number goes on top" },
      { id: "c", text: "11 × 4 = 44, because sharing means multiplying" },
      { id: "d", text: "11 − 4 = 7, because sharing means subtracting the groups" },
    ],
    correctChoiceId: "a",
  },
];
